{% set name = "cartopy_offlinedata" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # not used directly, just to have the bot keep us in sync with cartopy releases
  url: https://pypi.io/packages/source/c/cartopy/Cartopy-{{ version }}.tar.gz
  sha256: ce1d3a28a132e94c89ac33769a50f81f65634ab2bd40556317e15bd6cad1ce42

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.0.0
    - cartopy {{ version }}
  run:
    - python >=3.0.0
    - cartopy >={{ version }}

test:
  commands:
    # pick a few random things to check for
    - test -f $PREFIX/share/cartopy/shapefiles/natural_earth/physical/ne_10m_antarctic_ice_shelves_polys.shp
    - test -f $PREFIX/share/cartopy/shapefiles/natural_earth/physical/ne_10m_coastline.shp
    - test -f $PREFIX/share/cartopy/shapefiles/natural_earth/cultural/ne_50m_urban_areas.shp

about:
  home: https://scitools.org.uk/cartopy/docs/latest/
  summary: Offline data for using cartopy without an internet connection
  license: GPL-3.0-only
  license_file:
    - licenses/LICENSE_NACISCDN_NaturalEarth
    - licenses/LICENSE_NOAA_NGDC_GSHHS
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - xylar
    - willirath
