{% set name = "cartopy_offlinedata" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/willirath/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 533ad3194ad2fcb55ec961a5ead954d04de0ce13d82381437ad3951c19760383

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.0.0
    - pip
    - setuptools
    - cartopy >=0.18.0
  run:
    - python >=3.0.0
    - cartopy >=0.18.0

test:
  imports:
    - cartopy_userconfig
  commands:
    - download_cartopy_data.py --help

about:
  home: https://github.com/willirath/cartopy_offlinedata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Override cartopy.config to use offline data stored in the conda env.
  doc_url: https://github.com/willirath/cartopy_offlinedata
  dev_url: https://github.com/willirath/cartopy_offlinedata

extra:
  recipe-maintainers:
    - xylar
    - willirath
