{% set name = "cartopy_offlinedata" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/willirath/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3457fcee979a0ad584f4106dffac4d947c0419804bc03282e2edd777cee3f0c5

build:
  noarch: python
  number: 0

requirements:
  build:
    - bash
  host:
    - python
    - pip
    - setuptools
    - cartopy
    - bash
    - wget
  run:
    - python
    - cartopy

test:
  requires:
    - bash
  imports:
    - cartopy_userconfig
  commands:
    - download_cartopy_data.sh --help

about:
  home: https://github.com/willirath/cartopy_offlinedata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Override cartopy.config to use offline data stored in the conda env.
  doc_url: https://github.com/willirath/cartopy_offlinedata
  dev_url: https://github.com/willirath/cartopy_offlinedata

extra:
  recipe-maintainers:
    - xylar
    - willirath
