{% set name = "cartopy_offlinedata" %}
{% set version = "0.24.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # used for the download tool
  url: https://pypi.org/packages/source/c/cartopy/cartopy-{{ version }}.tar.gz
  sha256: e044e0e0fa76bb7afde937bec541743dcbf6b6f23b933a21ebddcd20cfffb755

build:
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - cartopy {{ version }}
  run:
    - python >={{ python_min }}
    - cartopy >={{ version }}

test:
  requires:
    - python {{ python_min }}
  commands:
    # pick a few random things to check for
    - test -f $PREFIX/share/cartopy/shapefiles/natural_earth/physical/ne_10m_antarctic_ice_shelves_polys.shp
    - test -f $PREFIX/share/cartopy/shapefiles/natural_earth/physical/ne_10m_coastline.shp
    - test -f $PREFIX/share/cartopy/shapefiles/natural_earth/cultural/ne_50m_urban_areas.shp

about:
  home: https://scitools.org.uk/cartopy/docs/latest/
  summary: Offline data for using cartopy without an internet connection
  license: GPL-3.0-only
  license_file:
    - licenses/LICENSE_NACISCDN_NaturalEarth
    - licenses/LICENSE_NOAA_NGDC_GSHHS
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/

extra:
  recipe-maintainers:
    - xylar
    - willirath
