travis:
  secure:
    BINSTAR_TOKEN: LNYb06Rdfi4bWdZcegDun2RmapF68dOfY3ipuQvEFy0f7phRPU/7E5Gu9p6TvsBb5DKIOgq68xkVEcMHTG8TsoCy67dlDJ/Y7Klc/ZN2wDa/HA3I29IHTG40LGl68tYUvdBCq8D8ppDvnyD/hQkfmqPK6TUmvxVUAztNFUXD+PD7IGagrfTWUp2IlHjYWEFuwJKhy7YaEDIkgml+s6j+X27S3QlvrO8ZwvkzgOTMoWaYwVZeHej0WRLgVxe8iAWMhdvE/P0Gk6Jjrgjz5AhBnHYWep4N0/MiHvX9YYoqifBWbA/qGegaQ+aFpi45VAUdhcX8uNo2qV6/h1iwL605y9urhYl3ZSSo7S+EC0iqlJbkHlGdr5UhPBKVntxMV1nnJYplSEnSHhAXTvyeq2pl4jU/vpoZhxEJbXov4PERS1hV2qq/sVtYZBW5FM/PsKdb7rjBYt8ptCsoXoNvZ3Y5r2BcBJ4vKLITubzCWwxCjmbYLrElSaDwvo392+ITYU4lw3i4k/XoOllcoM+fZIsTcEXcBmJRLR7Adiyvd4keq0KgsOo+8W7FFaj7wD1qum8kXA+FoWO+x7E9BuXQkRYVd/wMgYx5TqYRyq2INzVTShW/a8HsF0C+sbKgaC1SvERvUxP7vEoHipOszAzlrdCIrlJT3czO100uB4/iTxFgRK0=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
